name: ASP.NET API CI/CD 
 
on:  
   push: 
     branches: ["master"] 
   pull_request: 
     branches: ["master"] 
 
jobs: 
 
   build: 
      name: Compilação 
      runs-on: ubuntu-latest 
      steps: 
          - name: Checkout do código 
            uses: actions/checkout@v3 
          - name: Compilar 
            run: echo "Compilando a aplicação..." 
        
   test: 
      name: Testes 
      runs-on: ubuntu-latest 
      needs: build 
      steps: 
          - name: Checkout do código 
            uses: actions/checkout@v3 
          - name: Executar os testes 
            run: echo "Rodando os testes..." 
    
   deploy: 
      name: Implantação 
      runs-on: ubuntu-latest 
      needs: test 
      steps: 
          - name: Checkout do código 
            uses: actions/checkout@v3 
          - name: Implantação da aplicação 
            run: echo "Implatando o sistema em produção..." 
